DROP TABLE FILES;
CREATE TABLE FILES (
FILE_ID INTEGER NOT NULL AUTO_INCREMENT,
FILE_NAME VARCHAR(20) NOT NULL UNIQUE,
DESCRIPTION VARCHAR(500) NOT NULL,
URL VARCHAR(100) NOT NULL,
PRIMARY KEY (FILE_ID));
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File01.txt', 'This is a Descriptor1, This is a Descriptor1, This is a Descriptor1, This is a Descriptor1, This is a Descriptor1, This is a Descriptor1, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text01.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File02.txt', 'This is a Descriptor2, This is a Descriptor2, This is a Descriptor2, This is a Descriptor2, This is a Descriptor2, This is a Descriptor2, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text02.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File03.txt', 'This is a Descriptor3, This is a Descriptor3, This is a Descriptor3, This is a Descriptor3, This is a Descriptor3, This is a Descriptor3, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text03.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File04.txt', 'This is a Descriptor4, This is a Descriptor4, This is a Descriptor4, This is a Descriptor4, This is a Descriptor4, This is a Descriptor4, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text04.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File05.txt', 'This is a Descriptor5, This is a Descriptor5, This is a Descriptor5, This is a Descriptor5, This is a Descriptor5, This is a Descriptor5, Bla, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text05.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File06.txt', 'This is a Descriptor6, This is a Descriptor6, This is a Descriptor6, This is a Descriptor6, This is a Descriptor6, This is a Descriptor6, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text06.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File07.txt', 'This is a Descriptor7, This is a Descriptor7, This is a Descriptor7, This is a Descriptor7, This is a Descriptor7, This is a Descriptor7, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text07.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File08.txt', 'This is a Descriptor8, This is a Descriptor8, This is a Descriptor8, This is a Descriptor8, This is a Descriptor8, This is a Descriptor8, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text08.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File09.txt', 'This is a Descriptor9, This is a Descriptor9, This is a Descriptor9, This is a Descriptor9, This is a Descriptor9, This is a Descriptor9, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text09.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File10.txt', 'This is a Descriptor10, This is a Descriptor10, This is a Descriptor10, This is a Descriptor10, This is a Descriptor10, This is a Descriptor10, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text10.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File11.txt', 'This is a Descriptor11, This is a Descriptor11, This is a Descriptor11, This is a Descriptor11, This is a Descriptor11, This is a Descriptor11, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text11.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File12.txt', 'This is a Descriptor12, This is a Descriptor12, This is a Descriptor12, This is a Descriptor12, This is a Descriptor12, This is a Descriptor12, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text12.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File13.txt', 'This is a Descriptor13, This is a Descriptor13, This is a Descriptor13, This is a Descriptor13, This is a Descriptor13, This is a Descriptor13, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text13.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File14.txt', 'This is a Descriptor14, This is a Descriptor14, This is a Descriptor14, This is a Descriptor14, This is a Descriptor14, This is a Descriptor14, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text14.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File15.txt', 'This is a Descriptor15, This is a Descriptor15, This is a Descriptor15, This is a Descriptor15, This is a Descriptor15, This is a Descriptor15, Bla, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text15.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File16.txt', 'This is a Descriptor16, This is a Descriptor16, This is a Descriptor16, This is a Descriptor16, This is a Descriptor16, This is a Descriptor16, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text16.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File17.txt', 'This is a Descriptor17, This is a Descriptor17, This is a Descriptor17, This is a Descriptor17, This is a Descriptor17, This is a Descriptor17, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text17.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File18.txt', 'This is a Descriptor18, This is a Descriptor18, This is a Descriptor18, This is a Descriptor18, This is a Descriptor18, This is a Descriptor18, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text18.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File19.txt', 'This is a Descriptor19, This is a Descriptor19, This is a Descriptor19, This is a Descriptor19, This is a Descriptor19, This is a Descriptor19, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text19.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File20.txt', 'This is a Descriptor20, This is a Descriptor20, This is a Descriptor20, This is a Descriptor20, This is a Descriptor20, This is a Descriptor20, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text20.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File21.txt', 'This is a Descriptor21, This is a Descriptor21, This is a Descriptor21, This is a Descriptor21, This is a Descriptor21, This is a Descriptor21, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text21.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File22.txt', 'This is a Descriptor22, This is a Descriptor22, This is a Descriptor22, This is a Descriptor22, This is a Descriptor22, This is a Descriptor22, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text22.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File23.txt', 'This is a Descriptor23, This is a Descriptor23, This is a Descriptor23, This is a Descriptor23, This is a Descriptor23, This is a Descriptor23, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text23.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File24.txt', 'This is a Descriptor24, This is a Descriptor24, This is a Descriptor24, This is a Descriptor24, This is a Descriptor24, This is a Descriptor24, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text24.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File25.txt', 'This is a Descriptor25, This is a Descriptor25, This is a Descriptor25, This is a Descriptor25, This is a Descriptor25, This is a Descriptor25, Bla, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text25.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File26.txt', 'This is a Descriptor26, This is a Descriptor26, This is a Descriptor26, This is a Descriptor26, This is a Descriptor26, This is a Descriptor26, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text26.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File27.txt', 'This is a Descriptor27, This is a Descriptor27, This is a Descriptor27, This is a Descriptor27, This is a Descriptor27, This is a Descriptor27, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text27.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File28.txt', 'This is a Descriptor28, This is a Descriptor28, This is a Descriptor28, This is a Descriptor28, This is a Descriptor28, This is a Descriptor28, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text28.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File29.txt', 'This is a Descriptor29, This is a Descriptor29, This is a Descriptor29, This is a Descriptor29, This is a Descriptor29, This is a Descriptor29, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text29.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File30.txt', 'This is a Descriptor30, This is a Descriptor30, This is a Descriptor30, This is a Descriptor30, This is a Descriptor30, This is a Descriptor30, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text30.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File31.txt', 'This is a Descriptor31, This is a Descriptor31, This is a Descriptor31, This is a Descriptor31, This is a Descriptor31, This is a Descriptor31, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text31.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File32.txt', 'This is a Descriptor32, This is a Descriptor32, This is a Descriptor32, This is a Descriptor32, This is a Descriptor32, This is a Descriptor32, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text32.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File33.txt', 'This is a Descriptor33, This is a Descriptor33, This is a Descriptor33, This is a Descriptor33, This is a Descriptor33, This is a Descriptor33, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text33.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File34.txt', 'This is a Descriptor34, This is a Descriptor34, This is a Descriptor34, This is a Descriptor34, This is a Descriptor34, This is a Descriptor34, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text34.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File35.txt', 'This is a Descriptor35, This is a Descriptor35, This is a Descriptor35, This is a Descriptor35, This is a Descriptor35, This is a Descriptor35, Bla, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text35.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File36.txt', 'This is a Descriptor36, This is a Descriptor36, This is a Descriptor36, This is a Descriptor36, This is a Descriptor36, This is a Descriptor36, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text36.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File37.txt', 'This is a Descriptor37, This is a Descriptor37, This is a Descriptor37, This is a Descriptor37, This is a Descriptor37, This is a Descriptor37, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text37.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File38.txt', 'This is a Descriptor38, This is a Descriptor38, This is a Descriptor38, This is a Descriptor38, This is a Descriptor38, This is a Descriptor38, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text38.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File39.txt', 'This is a Descriptor39, This is a Descriptor39, This is a Descriptor39, This is a Descriptor39, This is a Descriptor39, This is a Descriptor39, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text39.txt');
INSERT INTO FILES(FILE_NAME, DESCRIPTION, URL) VALUES('File40.txt', 'This is a Descriptor40, This is a Descriptor40, This is a Descriptor40, This is a Descriptor40, This is a Descriptor40, This is a Descriptor40, Bla, Bla, Bla, Bla', 'file://localhost/home/hennadiy/Projects/java/FileRepositoryServer/files/text40.txt');