DROP TABLE USERS;
CREATE TABLE USERS (
ID INTEGER NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(30) NOT NULL UNIQUE,
PASSWORD VARCHAR(20) NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (ID));
INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('josmith', 'password', 'John', 'Smith');
INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('magross', 'password', 'Mary', 'Gross');
INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('bisandler', 'password', 'Bill', 'Sandler');
INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('safish', 'password', 'Samantha', 'Fish');
INSERT INTO USERS(USER_NAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('scwue', 'password', 'Scott', 'Wue');