DROP TABLE USERS;
CREATE TABLE USERS (
USER_ID INTEGER NOT NULL AUTO_INCREMENT,
USER_NAME VARCHAR(20) NOT NULL UNIQUE,
PASSWORD VARCHAR(96) NOT NULL,
ACCESS VARCHAR(6) NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
PRIMARY KEY (USER_ID));
